### ISSUE TITLE
Is this a production ready project that is maintained?

### ISSUE THREAD

**Issue by neiljaywarner** [JulianAssmann/flutter_gauges#4]
some of your wording makes it seem like this is not a good choice for production projects.
Should this wording be updated?  It may be outdated or less applicable, it seems like from the changelog and updates and other stuff it might be a good choice from production projects.
specifically in italics
'Note: This project serves as a training exercise for myself in order to better understand the inner workings of Flutter and learn how to write custom Widgets, Elements and RenderObjects from scratch. As a result, the API might change heavily and I may not know about best practices or optimal solutions for many problems.'

I appreciate the idea that of a disclaimer your solution might not be optimal but perhaps a slight wording change especially if it is more solid of a package than it was at the beginning 
Thanks

**Comment by JulianAssmann** [comment]
You can certainly use this package in production as it works just fine in its current state. However, if I have enough time to develop this project any further, I cannot guarantee a stable API, which is often seen as a requirement for the label *production ready*.

I hope this answers your question. If not, feel free to reopen the issue at any time.
